  ImGuiLayer.cpp
D:\C++\Cherno\Hazel\Hazel\src\Hazel\ImGui\ImGuiLayer.h(67,16): warning C4305: “初始化”: 从“double”到“float”截断
D:\C++\Cherno\Hazel\Hazel\src\Hazel\Objects\Objects.h(12,1): warning C4005: “PI”: 宏重定义
D:\C++\Cherno\Hazel\Hazel\src\Hazel\Renderer\Animation.h(3): message : 参见“PI”的前一个定义
D:\C++\Cherno\Hazel\Hazel\src\Hazel\ImGui\ImGuiLayer.cpp(1236,18): warning C4244: “初始化”: 从“float”转换到“int”，可能丢失数据
D:\C++\Cherno\Hazel\Hazel\src\Hazel\ImGui\ImGuiLayer.cpp(1724,113): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
assimp-vc142-mtd.lib(assimp-vc142-mtd.dll) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR 已在 Opengl32.lib(OPENGL32.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR 已在 Opengl32.lib(OPENGL32.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_VaBuildValue_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _Py_VaBuildValue_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_TrueStruct 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_SwappedOp 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_NotImplementedStruct 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_NoneStruct 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_FalseStruct 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_EllipsisObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_Dealloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _Py_Dealloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_CheckRecursiveCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _Py_CheckRecursiveCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_CheckRecursionLimit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__Py_BuildValue_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _Py_BuildValue_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyWeakref_RefType 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyWeakref_ProxyType 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyWeakref_CallableProxyType 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyTrash_thread_destroy_chain 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyTrash_thread_destroy_chain 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyTrash_thread_deposit_object 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyTrash_thread_deposit_object 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyTrash_destroy_chain 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyTrash_destroy_chain 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyTrash_deposit_object 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyTrash_deposit_object 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyThreadState_Prealloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyThreadState_Prealloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyThreadState_Init 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyThreadState_Init 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyState_AddModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyState_AddModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_NewVar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_NewVar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_GC_Resize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_GC_Resize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_GC_NewVar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_GC_NewVar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_GC_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_GC_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_GC_Malloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_GC_Malloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_CallMethod_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_CallMethod_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyObject_CallFunction_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyObject_CallFunction_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyErr_BadInternalCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyErr_BadInternalCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyArg_VaParse_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyArg_VaParse_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyArg_VaParseTupleAndKeywords_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyArg_VaParseTupleAndKeywords_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyArg_Parse_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyArg_Parse_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyArg_ParseTuple_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyArg_ParseTuple_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp__PyArg_ParseTupleAndKeywords_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: _PyArg_ParseTupleAndKeywords_SizeT 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_VaBuildValue 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_VaBuildValue 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_UTF8Mode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_SymtableString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_SymtableString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_SetRecursionLimit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_SetRecursionLimit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_SetPythonHome 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_SetPythonHome 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_SetProgramName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_SetProgramName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_SetPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_SetPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_ReprLeave 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_ReprLeave 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_ReprEnter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_ReprEnter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_NewInterpreter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_NewInterpreter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_MakePendingCalls 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_MakePendingCalls 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_Main 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_Main 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_IsInitialized 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_IsInitialized 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_InitializeEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_InitializeEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_Initialize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_Initialize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_IncRef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_IncRef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_HasFileSystemDefaultEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetVersion 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetVersion 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetRecursionLimit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetRecursionLimit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetPythonHome 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetPythonHome 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetProgramName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetProgramName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetProgramFullPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetProgramFullPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetPrefix 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetPrefix 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetPlatform 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetPlatform 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetExecPrefix 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetExecPrefix 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetCopyright 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetCopyright 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetCompiler 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetCompiler 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_GetBuildInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_GetBuildInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_FinalizeEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_FinalizeEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_Finalize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_Finalize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_FileSystemDefaultEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_FileSystemDefaultEncodeErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_FatalError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_FatalError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_Exit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_Exit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_EndInterpreter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_EndInterpreter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_EncodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_EncodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_DecodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_DecodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_DecRef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_DecRef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_CompileString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_CompileString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_BuildValue 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_BuildValue 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_AtExit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_AtExit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_Py_AddPendingCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: Py_AddPendingCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyZip_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyWrapper_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyWrapper_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyWrapperDescr_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyWeakref_NewRef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyWeakref_NewRef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyWeakref_NewProxy 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyWeakref_NewProxy 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyWeakref_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyWeakref_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_WriteChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_WriteChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Translate 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Translate 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Tailmatch 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Tailmatch 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Substring 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Substring 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Splitlines 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Splitlines 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Split 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Split 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_RichCompare 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_RichCompare 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Resize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Resize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Replace 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Replace 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_ReadChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_ReadChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_RSplit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_RSplit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_RPartition 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_RPartition 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Partition 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Partition 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Join 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Join 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_IsIdentifier 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_IsIdentifier 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_InternInPlace 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_InternInPlace 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_InternImmortal 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_InternImmortal 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_InternFromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_InternFromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_GetSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_GetSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_GetLength 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_GetLength 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_GetDefaultEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_GetDefaultEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromWideChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromWideChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromOrdinal 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromOrdinal 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromFormatV 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromFormatV 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromFormat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromFormat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FromEncodedObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FromEncodedObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Format 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Format 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FindChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FindChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Find 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Find 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FSDecoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FSDecoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_FSConverter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_FSConverter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_EncodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_EncodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_EncodeFSDefault 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_EncodeFSDefault 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_EncodeCodePage 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_EncodeCodePage 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUnicodeEscape 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUnicodeEscape 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF8Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF8Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF8 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF8 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF7Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF7Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF7 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF7 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF32Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF32Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF32 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF32 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF16Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF16Stateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeUTF16 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeUTF16 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeRawUnicodeEscape 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeRawUnicodeEscape 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeMBCSStateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeMBCSStateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeMBCS 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeMBCS 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeLocaleAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeLocaleAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeLocale 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeLatin1 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeLatin1 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeFSDefaultAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeFSDefaultAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeFSDefault 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeFSDefault 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeCodePageStateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeCodePageStateful 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeCharmap 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeCharmap 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_DecodeASCII 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_DecodeASCII 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Decode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Decode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Count 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Count 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_CompareWithASCIIString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_CompareWithASCIIString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Compare 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Compare 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_ClearFreeList 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_ClearFreeList 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_BuildEncodingMap 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_BuildEncodingMap 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsWideCharString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsWideCharString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsWideChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsWideChar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsUnicodeEscapeString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsUnicodeEscapeString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsUTF8String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsUTF8String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsUTF32String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsUTF32String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsUTF16String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsUTF16String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsUCS4Copy 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsUCS4Copy 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsUCS4 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsUCS4 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsRawUnicodeEscapeString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsRawUnicodeEscapeString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsMBCSString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsMBCSString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsLatin1String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsLatin1String 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsEncodedUnicode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsEncodedUnicode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsEncodedString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsEncodedString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsEncodedObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsEncodedObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsDecodedUnicode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsDecodedUnicode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsDecodedObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsDecodedObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsCharmapString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsCharmapString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AsASCIIString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AsASCIIString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_AppendAndDel 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_AppendAndDel 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicode_Append 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicode_Append 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeTranslateError_SetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeTranslateError_SetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeTranslateError_SetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeTranslateError_SetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeTranslateError_SetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeTranslateError_SetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeTranslateError_GetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeTranslateError_GetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeTranslateError_GetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeTranslateError_GetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeTranslateError_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeTranslateError_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeTranslateError_GetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeTranslateError_GetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_SetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_SetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_SetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_SetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_SetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_SetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_GetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_GetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_GetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_GetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_GetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_GetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeEncodeError_GetEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeEncodeError_GetEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_SetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_SetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_SetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_SetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_SetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_SetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_GetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_GetStart 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_GetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_GetReason 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_GetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_GetEnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_GetEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_GetEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyUnicodeDecodeError_Create 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyUnicodeDecodeError_Create 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_Ready 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_Ready 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_Modified 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_Modified 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_IsSubtype 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_IsSubtype 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_GetSlot 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_GetSlot 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_GetFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_GetFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_GenericNew 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_GenericNew 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_GenericAlloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_GenericAlloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_FromSpecWithBases 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_FromSpecWithBases 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_FromSpec 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_FromSpec 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyType_ClearCache 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyType_ClearCache 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTuple_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTuple_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_Pack 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTuple_Pack 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTuple_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_GetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTuple_GetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTuple_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTuple_ClearFreeList 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTuple_ClearFreeList 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTupleIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTraceBack_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTraceBack_Print 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTraceBack_Print 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyTraceBack_Here 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyTraceBack_Here 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThread_tss_set 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThread_tss_set 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThread_tss_is_created 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThread_tss_is_created 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThread_tss_get 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThread_tss_get 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThread_tss_free 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThread_tss_free 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThread_tss_delete 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThread_tss_delete 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThread_tss_create 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThread_tss_create 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThread_tss_alloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThread_tss_alloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_Swap 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_Swap 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_SetAsyncExc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_SetAsyncExc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_GetDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_GetDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_Get 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_Get 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_DeleteCurrent 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_DeleteCurrent 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_Delete 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_Delete 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyThreadState_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyThreadState_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_WriteStdout 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_WriteStdout 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_WriteStderr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_WriteStderr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_SetPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_SetPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_SetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_SetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_SetArgvEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_SetArgvEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_SetArgv 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_SetArgv 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_ResetWarnOptions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_ResetWarnOptions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_HasWarnOptions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_HasWarnOptions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_GetXOptions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_GetXOptions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_GetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_FormatStdout 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_FormatStdout 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_FormatStderr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_FormatStderr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_AddXOption 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_AddXOption 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_AddWarnOptionUnicode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_AddWarnOptionUnicode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySys_AddWarnOption 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySys_AddWarnOption 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySuper_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyStructSequence_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyStructSequence_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyStructSequence_NewType 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyStructSequence_NewType 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyStructSequence_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyStructSequence_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyStructSequence_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyStructSequence_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyState_RemoveModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyState_RemoveModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyState_FindModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyState_FindModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyState_AddModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyState_AddModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySlice_Unpack 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySlice_Unpack 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySlice_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySlice_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySlice_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySlice_GetIndicesEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySlice_GetIndicesEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySlice_GetIndices 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySlice_GetIndices 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySlice_AdjustIndices 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySlice_AdjustIndices 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySet_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_Pop 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySet_Pop 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySet_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_Discard 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySet_Discard 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySet_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySet_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySet_Add 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySet_Add 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySetIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Tuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Tuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_SetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_SetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Repeat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Repeat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_List 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_List 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Length 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Length 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Index 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Index 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_InPlaceRepeat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_InPlaceRepeat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_InPlaceConcat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_InPlaceConcat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_In 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_In 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_GetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_GetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Fast 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Fast 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_DelSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_DelSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Count 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Count 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySequence_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySequence_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySeqIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PySeqIter_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PySeqIter_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyReversed_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyRange_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyRangeIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyProperty_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyParser_SimpleParseStringFlagsFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyParser_SimpleParseStringFlagsFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyParser_SimpleParseStringFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyParser_SimpleParseStringFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyParser_SimpleParseFileFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyParser_SimpleParseFileFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Str 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Str 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_SetAttrString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_SetAttrString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_SetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_SetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_SelfIter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_SelfIter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_RichCompareBool 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_RichCompareBool 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_RichCompare 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_RichCompare 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Repr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Repr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Realloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Realloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Not 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Not 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Malloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Malloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Length 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Length 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_IsTrue 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_IsTrue 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_IsSubclass 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_IsSubclass 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_IsInstance 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_IsInstance 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_InitVar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_InitVar 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Init 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Init 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_HashNotImplemented 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_HashNotImplemented 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Hash 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Hash 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_HasAttrString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_HasAttrString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_HasAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_HasAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GetIter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GetIter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GetAttrString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GetAttrString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GenericSetDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GenericSetDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GenericSetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GenericSetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GenericGetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GenericGetAttr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GC_UnTrack 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GC_UnTrack 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GC_Track 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GC_Track 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_GC_Del 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_GC_Del 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Free 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Free 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Format 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Format 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Dir 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Dir 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_DelItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_DelItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_ClearWeakRefs 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_ClearWeakRefs 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_CheckReadBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_CheckReadBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Calloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Calloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_CallObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_CallObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_CallMethodObjArgs 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_CallMethodObjArgs 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_CallMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_CallMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_CallFunctionObjArgs 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_CallFunctionObjArgs 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_CallFunction 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_CallFunction 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Call 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Call 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_Bytes 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_Bytes 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_AsWriteBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_AsWriteBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_AsReadBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_AsReadBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_AsFileDescriptor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_AsFileDescriptor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_AsCharBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_AsCharBuffer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyObject_ASCII 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyObject_ASCII 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_vsnprintf 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_vsnprintf 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_strtoul 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_strtoul 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_strtol 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_strtol 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_string_to_double 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_string_to_double 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_snprintf 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_snprintf 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_setsig 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_setsig 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_mystrnicmp 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_mystrnicmp 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_mystricmp 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_mystricmp 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_getsig 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_getsig 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_double_to_string 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_double_to_string 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_ReadlineFunctionPointer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_InterruptOccurred 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_InterruptOccurred 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_InputHook 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_InitInterrupts 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_InitInterrupts 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_FSPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_FSPath 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyOS_AfterFork 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyOS_AfterFork 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODict_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODict_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyODict_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODict_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyODict_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODict_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyODict_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODictValues_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODictKeys_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODictIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyODictItems_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Xor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Xor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_TrueDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_TrueDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_ToBase 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_ToBase 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Subtract 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Subtract 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Rshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Rshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Remainder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Remainder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Power 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Power 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Positive 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Positive 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Or 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Or 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Negative 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Negative 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Multiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Multiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_MatrixMultiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_MatrixMultiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Lshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Lshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Long 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Long 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Invert 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Invert 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Index 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Index 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceXor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceXor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceTrueDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceTrueDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceSubtract 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceSubtract 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceRshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceRshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceRemainder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceRemainder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlacePower 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlacePower 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceOr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceOr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceMultiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceMultiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceMatrixMultiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceMatrixMultiply 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceLshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceLshift 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceFloorDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceFloorDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceAnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceAnd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_InPlaceAdd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_InPlaceAdd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_FloorDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_FloorDivide 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Float 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Float 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Divmod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Divmod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_AsSsize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_AsSsize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_And 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_And 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Add 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Add 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyNumber_Absolute 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyNumber_Absolute 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_SetDocString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_SetDocString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_NewObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_NewObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_GetState 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_GetState 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_GetNameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_GetNameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_GetName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_GetName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_GetFilenameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_GetFilenameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_GetFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_GetFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_GetDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_GetDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_GetDef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_GetDef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_FromDefAndSpec2 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_FromDefAndSpec2 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_ExecDef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_ExecDef 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_Create2 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_Create2 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_AddStringConstant 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_AddStringConstant 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_AddObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_AddObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_AddIntConstant 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_AddIntConstant 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModule_AddFunctions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModule_AddFunctions 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModuleDef_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyModuleDef_Init 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyModuleDef_Init 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMethodDescr_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMemoryView_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMemoryView_GetContiguous 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMemoryView_GetContiguous 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMemoryView_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMemoryView_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMemoryView_FromMemory 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMemoryView_FromMemory 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMemberDescr_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMem_Realloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMem_Realloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMem_Malloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMem_Malloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMem_Free 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMem_Free 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMem_Calloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMem_Calloc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_Values 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_Values 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_SetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_SetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_Length 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_Length 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_Keys 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_Keys 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_Items 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_Items 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_HasKeyString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_HasKeyString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_HasKey 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_HasKey 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_GetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_GetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMapping_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyMapping_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyMap_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_GetInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_GetInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromVoidPtr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromVoidPtr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromUnsignedLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromUnsignedLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromUnsignedLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromUnsignedLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromSsize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromSsize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromSize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromSize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_FromDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_FromDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsVoidPtr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsVoidPtr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsUnsignedLongMask 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsUnsignedLongMask 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsUnsignedLongLongMask 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsUnsignedLongLongMask 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsUnsignedLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsUnsignedLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsUnsignedLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsUnsignedLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsSsize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsSsize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsSize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsSize_t 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsLongLongAndOverflow 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsLongLongAndOverflow 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsLongLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsLongAndOverflow 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsLongAndOverflow 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLong_AsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyLong_AsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyLongRangeIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_Sort 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_Sort 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_SetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_SetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_Reverse 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_Reverse 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_Insert 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_Insert 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_GetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_GetSlice 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_AsTuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_AsTuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyList_Append 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyList_Append 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyListRevIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyListIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyIter_Next 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyIter_Next 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyIter_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyIter_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyInterpreterState_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyInterpreterState_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyInterpreterState_GetID 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyInterpreterState_GetID 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyInterpreterState_Delete 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyInterpreterState_Delete 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyInterpreterState_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyInterpreterState_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyIndex_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyIndex_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ReloadModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ReloadModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ImportModuleNoBlock 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ImportModuleNoBlock 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ImportModuleLevelObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ImportModuleLevelObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ImportModuleLevel 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ImportModuleLevel 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ImportModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ImportModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ImportFrozenModuleObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ImportFrozenModuleObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ImportFrozenModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ImportFrozenModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_Import 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_Import 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_GetModuleDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_GetModuleDict 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_GetModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_GetModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_GetMagicTag 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_GetMagicTag 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_GetMagicNumber 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_GetMagicNumber 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_GetImporter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_GetImporter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ExecCodeModuleWithPathnames 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ExecCodeModuleWithPathnames 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ExecCodeModuleObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ExecCodeModuleObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ExecCodeModuleEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ExecCodeModuleEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_ExecCodeModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_ExecCodeModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_Cleanup 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_Cleanup 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_AppendInittab 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_AppendInittab 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_AddModuleObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_AddModuleObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyImport_AddModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyImport_AddModule 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyGetSetDescr_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyGILState_Release 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyGILState_Release 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyGILState_GetThisThreadState 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyGILState_GetThisThreadState 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyGILState_Ensure 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyGILState_Ensure 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyGC_Collect 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyGC_Collect 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFrozenSet_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFrozenSet_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFrozenSet_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFloat_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFloat_GetMin 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFloat_GetMin 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFloat_GetMax 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFloat_GetMax 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFloat_GetInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFloat_GetInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFloat_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFloat_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFloat_FromDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFloat_FromDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFloat_AsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFloat_AsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFilter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFile_WriteString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFile_WriteString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFile_WriteObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFile_WriteObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFile_GetLine 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFile_GetLine 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyFile_FromFd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyFile_FromFd 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyException_SetTraceback 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyException_SetTraceback 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyException_SetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyException_SetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyException_SetCause 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyException_SetCause 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyException_GetTraceback 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyException_GetTraceback 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyException_GetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyException_GetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyException_GetCause 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyException_GetCause 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExceptionClass_Name 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyExceptionClass_Name 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ZeroDivisionError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_WindowsError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_Warning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ValueError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_UserWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_UnicodeWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_UnicodeTranslateError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_UnicodeError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_UnicodeEncodeError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_UnicodeDecodeError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_UnboundLocalError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_TypeError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_TimeoutError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_TabError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_SystemExit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_SystemError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_SyntaxWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_SyntaxError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_StopIteration 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_StopAsyncIteration 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_RuntimeWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_RuntimeError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ResourceWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ReferenceError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_RecursionError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ProcessLookupError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_PermissionError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_PendingDeprecationWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_OverflowError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_OSError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_NotImplementedError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_NotADirectoryError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_NameError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ModuleNotFoundError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_MemoryError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_LookupError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_KeyboardInterrupt 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_KeyError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_IsADirectoryError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_InterruptedError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_IndexError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_IndentationError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ImportWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ImportError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_IOError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_GeneratorExit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_FutureWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_FloatingPointError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_FileNotFoundError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_FileExistsError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_Exception 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_EnvironmentError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_EOFError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_DeprecationWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ConnectionResetError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ConnectionRefusedError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ConnectionError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ConnectionAbortedError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ChildProcessError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_BytesWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_BufferError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_BrokenPipeError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_BlockingIOError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_BaseException 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_AttributeError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_AssertionError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyExc_ArithmeticError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_ThreadsInitialized 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_ThreadsInitialized 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_SaveThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_SaveThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_RestoreThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_RestoreThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_ReleaseThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_ReleaseThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_ReleaseLock 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_ReleaseLock 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_InitThreads 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_InitThreads 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_GetLocals 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_GetLocals 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_GetGlobals 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_GetGlobals 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_GetFuncName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_GetFuncName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_GetFuncDesc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_GetFuncDesc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_GetFrame 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_GetFrame 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_GetBuiltins 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_GetBuiltins 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_EvalFrameEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_EvalFrameEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_EvalFrame 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_EvalFrame 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_EvalCodeEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_EvalCodeEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_EvalCode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_EvalCode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_CallObjectWithKeywords 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_CallObjectWithKeywords 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_CallMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_CallMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_CallFunction 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_CallFunction 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_AcquireThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_AcquireThread 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEval_AcquireLock 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyEval_AcquireLock 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_WriteUnraisable 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_WriteUnraisable 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_WarnFormat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_WarnFormat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_WarnExplicit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_WarnExplicit 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_WarnEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_WarnEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SyntaxLocationEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SyntaxLocationEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SyntaxLocation 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SyntaxLocation 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetNone 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetNone 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetInterrupt 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetInterrupt 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetImportErrorSubclass 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetImportErrorSubclass 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetImportError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetImportError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetFromWindowsErrWithFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetFromWindowsErrWithFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetFromWindowsErr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetFromWindowsErr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetFromErrnoWithFilenameObjects 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetFromErrnoWithFilenameObjects 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetFromErrnoWithFilenameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetFromErrnoWithFilenameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetFromErrnoWithFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetFromErrnoWithFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetFromErrno 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetFromErrno 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetExcInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetExcInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetExcFromWindowsErrWithFilenameObjects 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetExcFromWindowsErrWithFilenameObjects 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetExcFromWindowsErrWithFilenameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetExcFromWindowsErrWithFilenameObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetExcFromWindowsErrWithFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetExcFromWindowsErrWithFilename 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_SetExcFromWindowsErr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_SetExcFromWindowsErr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_Restore 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_Restore 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_ResourceWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_ResourceWarning 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_ProgramText 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_ProgramText 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_PrintEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_PrintEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_Print 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_Print 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_Occurred 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_Occurred 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_NormalizeException 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_NormalizeException 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_NoMemory 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_NoMemory 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_NewExceptionWithDoc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_NewExceptionWithDoc 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_NewException 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_NewException 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_GivenExceptionMatches 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_GivenExceptionMatches 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_GetExcInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_GetExcInfo 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_FormatV 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_FormatV 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_Format 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_Format 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_Fetch 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_Fetch 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_ExceptionMatches 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_ExceptionMatches 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_Display 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_Display 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_CheckSignals 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_CheckSignals 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_BadInternalCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_BadInternalCall 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyErr_BadArgument 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyErr_BadArgument 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEnum_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyEllipsis_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Values 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Values 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Update 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Update 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_SetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_SetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_SetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Next 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Next 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_MergeFromSeq2 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_MergeFromSeq2 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Merge 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Merge 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Keys 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Keys 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Items 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Items 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_GetItemWithError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_GetItemWithError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_GetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_GetItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_GetItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_DelItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_DelItemString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_DelItem 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Copy 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Copy 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Contains 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDict_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDict_Clear 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictValues_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictProxy_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictProxy_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDictProxy_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictKeys_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictIterValue_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictIterKey_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictIterItem_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDictItems_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDescr_NewMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDescr_NewMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDescr_NewMember 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDescr_NewMember 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDescr_NewGetSet 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDescr_NewGetSet 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyDescr_NewClassMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyDescr_NewClassMethod 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyComplex_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyComplex_RealAsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyComplex_RealAsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyComplex_ImagAsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyComplex_ImagAsDouble 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyComplex_FromDoubles 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyComplex_FromDoubles 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_XMLCharRefReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_XMLCharRefReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_StrictErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_StrictErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_StreamWriter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_StreamWriter 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_StreamReader 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_StreamReader 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_ReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_ReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_RegisterError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_RegisterError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_Register 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_Register 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_NameReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_NameReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_LookupError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_LookupError 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_KnownEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_KnownEncoding 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_IncrementalEncoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_IncrementalEncoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_IncrementalDecoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_IncrementalDecoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_IgnoreErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_IgnoreErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_Encoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_Encoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_Encode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_Encode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_Decoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_Decoder 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_Decode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_Decode 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCodec_BackslashReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCodec_BackslashReplaceErrors 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyClassMethodDescr_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_SetPointer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_SetPointer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_SetName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_SetName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_SetDestructor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_SetDestructor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_SetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_SetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_IsValid 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_IsValid 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_Import 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_Import 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_GetPointer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_GetPointer 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_GetName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_GetName 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_GetDestructor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_GetDestructor 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCapsule_GetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCapsule_GetContext 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCallable_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCallable_Check 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCallIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCallIter_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCallIter_New 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCFunction_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCFunction_NewEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCFunction_NewEx 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCFunction_GetSelf 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCFunction_GetSelf 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCFunction_GetFunction 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCFunction_GetFunction 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCFunction_GetFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCFunction_GetFlags 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCFunction_ClearFreeList 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCFunction_ClearFreeList 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyCFunction_Call 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyCFunction_Call 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_Repr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_Repr 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_FromStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_FromStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_FromString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_FromFormatV 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_FromFormatV 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_FromFormat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_FromFormat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_DecodeEscape 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_DecodeEscape 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_ConcatAndDel 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_ConcatAndDel 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_AsStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_AsStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytes_AsString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBytes_AsString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBytesIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArray_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArray_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyByteArray_Size 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArray_Resize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyByteArray_Resize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArray_FromStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyByteArray_FromStringAndSize 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArray_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyByteArray_FromObject 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArray_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyByteArray_Concat 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArray_AsString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyByteArray_AsString 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyByteArrayIter_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBool_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBool_FromLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyBool_FromLong 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyBaseObject_Type 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyArg_ValidateKeywordArguments 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyArg_ValidateKeywordArguments 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyArg_VaParseTupleAndKeywords 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyArg_VaParseTupleAndKeywords 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyArg_VaParse 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyArg_VaParse 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyArg_UnpackTuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyArg_UnpackTuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyArg_ParseTupleAndKeywords 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyArg_ParseTupleAndKeywords 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyArg_ParseTuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyArg_ParseTuple 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: __imp_PyArg_Parse 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python3.lib(python3.dll) : warning LNK4006: PyArg_Parse 已在 python3.lib(python3.dll) 中定义；已忽略第二个定义
python38.lib(python38.dll) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR 已在 Opengl32.lib(OPENGL32.dll) 中定义；已忽略第二个定义
  Hazel.vcxproj -> D:\C++\Cherno\Hazel\Hazel\..\x64\Release\Hazel.lib
